//LOGIN
export const LOGIN_USER = 'login_user'
export const REGISTER_USER = 'register_user'
export const AUTH_USER = 'auth_user'
export const LOGOUT_USER = 'logout_user'
export const FETCH_USERS = 'FETCH_USERS'

//ASEGURADOS
export const FETCH_ASEGURADOS = 'FETCH_ASEGURADOS'
export const FILTER_ASEGURADOS_BY_CATEGORY = 'FILTER_ASEGURADOS_BY_CATEGORY'
export const ADD_ASEGURADO = 'ADD_ASEGURADO '
export const DELETE_ASEGURADO  = 'DELETE_ASEGURADO '

//TERCEROS
export const FETCH_TERCEROS = 'FETCH_TERCEROS'
export const FILTER_TERCEROS_BY_CATEGORY = 'FILTER_TERCEROS_BY_CATEGORY'
export const ADD_TERCERO = 'ADD_TERCERO'
export const DELETE_TERCERO = 'DELETE_TERCERO'

//VEHICULOS
export const FETCH_VEHICULOS = 'FETCH_VEHICULOS'
export const FILTER_VEHICULOS_BY_CATEGORY = 'FILTER_VEHICULOS_BY_CATEGORY'
export const ADD_VEHICULO = 'ADD_VEHICULO'
export const DELETE_VEHICULO = 'DELETE_VEHICULO'

//NOVEDADES
export const FETCH_NOVEDADES = 'FETCH_NOVEDADES'
export const FILTER_NOVEDADES_BY_CATEGORY = 'FILTER_NOVEDADES_BY_CATEGORY'
export const ADD_NOVEDAD = 'ADD_NOVEDAD'
export const DELETE_NOVEDAD = 'DELETE_NOVEDAD'

//SINIESTROS
export const FETCH_SINIESTROS = 'FETCH_SINIESTROS'
export const FILTER_SINIESTROS_BY_CATEGORY = 'FILTER_SINIESTROS_BY_CATEGORY'
export const ADD_SINIESTRO = 'ADD_SINIESTRO'
export const DELETE_SINIESTRO = 'DELETE_SINIESTRO'

//ENTREVISTAS
export const FETCH_ENTREVISTAS = 'FETCH_ENTREVISTAS'
export const FILTER_ENTREVISTAS_BY_CATEGORY = 'FILTER_ENTREVISTAS_BY_CATEGORY'
export const ADD_ENTREVISTA = 'ADD_ENTREVISTA'
export const DELETE_ENTREVISTA = 'DELETE_ENTREVISTA'
